name: Release to Github

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install # no dependencies, but just in case for future

      - run: yarn build


      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Build ${{ github.event.repository.updated_at}}
          files: |
            dist/chrome-extension.zip
            dist/firefox-extension.zip
